CREATE DATABASE post_je;

CREATE TABLE IF NOT EXISTS location (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
    name VARCHAR(50) NOT NULL,
    postcode INT NOT NULL,
);

CREATE TABLE IF NOT EXISTS courier (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS dropOff (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
    locationId INT NOT NULL,
    courierId INT NOT NULL,
    lat FLOAT NOT NULL,
    long FLOAT NOT NULL,
    FOREIGN KEY (locationId) REFERENCES location(id),
    FOREIGN KEY (courierId) REFERENCES courier(id)
);

CREATE TABLE IF NOT EXISTS package (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
    courierId INT NOT NULL,
    length INT NOT NULL,
    width INT NOT NULL,
    height INT NOT NULL,
    price INT NOT NULL,
    weight INT NOT NULL,
    link VARCHAR(100) NOT NULL,
    FOREIGN KEY (courierId) REFERENCES courier(id)
);